name: Qrisp unit tests via Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.9.16"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e ./
          pip install --upgrade pennylane-catalyst
          pip install qiskit-aer
          pip install jax==0.4.28
          pip install jaxlib==0.4.28
          pip install pyscf
          pip install qiskit-iqm
          pip install stim
      - name: Test with pytest
        run: |
          pytest
